parameters:
    env(mailer_use): ''

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%env(MAILER_USER)%"
        sender_name: "%env(MAILER_USER)%"
    profile:
        form:
            type: App\Form\ProfileType
    service:
        mailer: App\Service\MailerService